### PR TITLE
Fix Typo 

### PR DESCRIPTION
**Pull request by sheela-svmx**
Fix Typo

### CODE REVIEW

**Comment by sheela-svmx** [comment]
@joshsylvester @mallik-svmx

**Comment by sheela-svmx** [comment]
@shao looks like only you have access to merge, can you please merge this one? Also is it possible to give access to Josh to merge this

**Comment by shao** [comment]
All UI team members can merge now.

**Comment by sheela-svmx** [comment]
Thanks @shao

**Pull request merged**
